services:
  db_company_management:
    image: postgres:16
    container_name: db_company_management
    environment:
      POSTGRES_USER: company_user
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: db_company_management
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  
    restart: always

  company_management_backend:
    build: .services/company_management/backend
    container_name: company_management_backend
    depends_on:
      - db_company_management
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db_company_management
      DB_PORT: 5432
      DB_USER: company_user
      DB_PASS: pass1234
      DB_NAME: db_company_management

  product_service:
    build: 
      context: ./services/product
      args:
        - DATABASE_URL=postgresql://postgres:password@product_db:5432/productdb
    container_name: product_service
    ports:
      - "8005:8000"
    depends_on:
      - product_db
    networks:
      - internal

  product_db:
    image: postgres:13-alpine
    container_name: product_configuration_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - internal

  product_tests:
    build: ./services/product
    container_name: product_tests
    command: ["pytest", "-v", "--tb=short", "-p", "no:cacheprovider"] 
    depends_on:
      product_db:
        condition: service_healthy
    networks:
      - internal
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - product_db
    networks:
      - internal

volumes:
  pgdata:

networks:
  internal:
    driver: bridge