services:
  db_company_management:
    image: postgres:16
    container_name: db_company_management
    environment:
      POSTGRES_USER: company_user
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: db_company_management
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  
    restart: always

  company_management_backend:
    build: services/company_management
    container_name: company_management_backend
    depends_on:
      - db_company_management
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db_company_management
      DB_PORT: 5432
      DB_USER: company_user
      DB_PASS: pass1234
      DB_NAME: db_company_management



  product_service:
    build: ./services/product
    container_name: product_service
    environment:
      # Connect to the dedicated DB instance
      - DATABASE_URL=postgresql://postgres:password@product_db:5432/productdb
    ports:
      - "8000:8000"
    depends_on:
      - product_db

  product_db:
    image: postgres:13-alpine
    container_name: product_configuration_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  user_db:
    image: postgres:13
    container_name: user_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${USER_DB_NAME}
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  user_service:
    build: ./services/user_management
    env_file:
      - .env
    container_name: user_service
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${USER_DB_HOST}
      DB_PORT: ${USER_DB_PORT}
      DB_NAME: ${USER_DB_NAME}
    depends_on:
      - user_db
    ports:
      - "8003:8000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - user_db
      - product_db

   

volumes:
  pgdata_user:
