name: "Monorepo Service Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  filter:
    name: "Determine Changed Services"
    runs-on: ubuntu-latest
    outputs:
      company: ${{ steps.paths.outputs.company }}
      product: ${{ steps.paths.outputs.product }}
      user: ${{ steps.paths.outputs.user }}
      gateway: ${{ steps.paths.outputs.gateway }}
      notification: ${{ steps.paths.outputs.notification }}
      policy: ${{ steps.paths.outputs.policy }}
    steps:
      - uses: actions/checkout@v3
      - name: "Filter paths"
        id: paths
        uses: dorny/paths-filter@v2
        with:
          filters: |
            company:
              - 'services/company_management/**'
            product:
              - 'services/product/**'
            user:
              - 'services/user_management/**'
            gateway:
              - 'services/gateway/**'
            notification:
              - 'services/notification/**'
            policy:
              - 'services/policy/**'

  test-services:
    name: "Run Changed Service Tests"
    needs: filter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: policy
            changed: ${{ needs.filter.outputs.policy }}
            service: policy_tests
            args: ""
          - name: company
            changed: ${{ needs.filter.outputs.company }}
            service: company_tests
            args: ""
          - name: product
            changed: ${{ needs.filter.outputs.product }}
            service: product_tests
            args: ""
          - name: user
            changed: ${{ needs.filter.outputs.user }}
            service: user_service
            args: "pytest services/user_management"
          - name: gateway
            changed: ${{ needs.filter.outputs.gateway }}
            service: gateway
            args: ""
          - name: notification
            changed: ${{ needs.filter.outputs.notification }}
            service: notification_service
            args: "pytest services/notification"
    # only run matrix entries where the path-filter flagged changes
    if: ${{ matrix.changed == 'true' }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose plugin (V2)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Run ${{ matrix.name }} tests
        run: |
          docker compose run --rm ${{ matrix.service }} ${{ matrix.args }}
